GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC;
GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC;
GO
EXECUTE sys.sp_configure 'SHOW ADVANCED OPTIONS',     1 RECONFIGURE WITH OVERRIDE
GO
EXECUTE sys.sp_configure 'OLE AUTOMATION PROCEDURES', 1 RECONFIGURE WITH OVERRIDE
GO
EXECUTE sys.sp_configure 'SHOW ADVANCED OPTIONS',     0 RECONFIGURE WITH OVERRIDE
GO